ZOOLIB_DIR = ../../..
MISC_DIR = $(ZOOLIB_DIR)/src_other/misc
NPAINTER_DIR = $(ZOOLIB_DIR)/src_other/npainter
PROJECT_DIR = $(ZOOLIB_DIR)/samples/paintertest/paintertest_src

include ${PROJECT_DIR}/realmake

include $(ZOOLIB_DIR)/tools/zmake/zmake.engine
