ZOOLIB_DIR = ../../..
PROJECT_DIR = ${ZOOLIB_DIR}/samples/buttonmessage/buttonmessage_src
ZCONFIG_ROOT = ${APP_ROOT}/zconfig

include ${PROJECT_DIR}/realmake

include ${ZOOLIB_DIR}/tools/zmake/zmake.engine
